#ifndef _MOUNT_ERR_H
#define _MOUNT_ERR_H 1

enum MOUNT_ERR {
	MOUNT_ERR_TOTAL_FAILURE = -1,
	MOUNT_ERR_MOUNTED_SUBPOINTS = -2,
	MOUNT_ERR_BUSY = -3,
	MOUNT_ERR_ALREADY_MOUNTED = -4,
	MOUNT_ERR_DEVICE_ERROR = -5,
	MOUNT_ERR_FILESYS_ERROR = -6,

	MOUNT_ERR_FREE_ERRORCODE = -0x10000 // ;)
};

#endif
